# Generated by Django 5.2.4 on 2025-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
