# Generated by Django 5.2.4 on 2025-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_public_posts',
            field=models.BooleanField(default=True, help_text='Allow any authenticated user to post in this group'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
